### ISSUE TITLE
“isa&&Class&&meta-class 初步认识” 一文中可能有几处错误

### ISSUE THREAD

**Issue by aktue** [miniLV/Interview-series#1]
在这里学到了很多东西，十分感谢作者。

在看 “isa&&Class&&meta-class 初步认识” 时，我认为有几处错误，不知是否我的理解有问题：

140 行：`[MNSubclass superClassMethod];` // 移到 144 行的下面
232 行：[subclass subclassInstanceMethod]; // [subclass compareSelfWithSuperclass];
253 行：通过`isa`找到了 // 通过`superclass`找到了（下面的图里也写错了）

PS：另外这篇文章的小错误（如错别字），相对其他几篇来说有些多，虽然大多不影响理解，但希望作者有时间可以看一下。。

**Comment by miniLV** [comment]
哎呦兄弟，真的太感谢你的细心提示，因为这些文章前后整理好几天才能撸一篇出来，确实有写没注意，自己review的时候还真没注意，已经修改，如果还有笔误的地方欢迎指正~多谢支持~
